# Generated by Django 5.1.5 on 2025-03-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_disciplina_carga_horaria_disciplina_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.CharField(default='desenvolvimento de sistemas', max_length=50),
        ),
    ]
